/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "All Receiver": {
        "en": `All Receiver`,
        "de": `Alle Empfänger`,
        "ru": `Весь приемник`,
        "pt": `Todo o receptor`,
        "nl": `All Receiver`,
        "fr": `Tout récepteur`,
        "it": `Tutto il ricevitore`,
        "es": `Todo receptor`,
        "pl": `Wszystkie odbiorniki`,
        "zh-cn": `所有接收者`
    },
    "E-mail address": {
        "en": `E-mail address`,
        "de": `E-Mail Adresse`,
        "ru": `Адрес электронной почты`,
        "pt": `Endereço de e-mail`,
        "nl": `E-mailadres`,
        "fr": `Adresse électronique`,
        "it": `Indirizzo email`,
        "es": `Dirección de correo electrónico`,
        "pl": `Adres e-mail`,
        "zh-cn": `电子邮件地址`
    },
    "Notifications": {
        "en": `Notifications`,
        "de": `Benachrichtigungen`,
        "ru": `Уведомления`,
        "pt": `Notificações`,
        "nl": `meldingen`,
        "fr": `Les notifications`,
        "it": `notifiche`,
        "es": `Notificaciones`,
        "pl": `Powiadomienia`,
        "zh-cn": `通知`
    },
    "Password": {
        "en": `Password`,
        "de": `Passwort`,
        "ru": `пароль`,
        "pt": `Senha`,
        "nl": `Wachtwoord`,
        "fr": `Mot de passe`,
        "it": `Parola d'ordine`,
        "es": `Contraseña`,
        "pl": `Hasło`,
        "zh-cn": `密码`
    },
    "device ID (optional)": {
        "en": `Device ID (optional)`,
        "de": `Device ID (optional)`,
        "ru": `Идентификатор устройства (необязательно)`,
        "pt": `ID do dispositivo (opcional)`,
        "nl": `Apparaat-ID (optioneel)`,
        "fr": `ID de périphérique (facultatif)`,
        "it": `ID dispositivo (opzionale)`,
        "es": `ID del dispositivo (opcional)`,
        "pl": `ID urządzenia (opcjonalnie)`,
        "zh-cn": `设备ID（可选）`
    },
    "email instance": {
        "en": `E-Mail Instance`,
        "de": `E-Mail Instanz`,
        "ru": `E-Mail Instance`,
        "pt": `Instância de email`,
        "nl": `E-mailinstantie`,
        "fr": `Instance de courrier électronique`,
        "it": `Istanza di posta elettronica`,
        "es": `Instancia de correo electrónico`,
        "pl": `Instancja e-mail`,
        "zh-cn": `电子邮件实例`
    },
    "email receiver": {
        "en": `E-Mail Receiver`,
        "de": `E-Mail Empfänger`,
        "ru": `E-Mail Receiver`,
        "pt": `Receptor de e-mail`,
        "nl": `E-mailontvanger`,
        "fr": `Destinataire du courrier électronique`,
        "it": `Ricevitore di posta elettronica`,
        "es": `Receptor de correo electrónico`,
        "pl": `Odbiornik e-mail`,
        "zh-cn": `电子邮件接收器`
    },
    "email sender": {
        "en": `E-Mail Sender`,
        "de": `E-Mail Absender`,
        "ru": `E-Mail Sender`,
        "pt": `Remetente de e-mail`,
        "nl": `E-mail afzender`,
        "fr": `Expéditeur de courrier électronique`,
        "it": `Mittente e-mail`,
        "es": `E-mail remitente`,
        "pl": `E-Mail Sender`,
        "zh-cn": `电子邮件发件人`
    },
    "notifications type": {
        "en": `Notifications Type`,
        "de": `Benachrichtigungsart`,
        "ru": `Тип уведомлений`,
        "pt": `Tipo de Notificações`,
        "nl": `Meldingen Type`,
        "fr": `Type de notifications`,
        "it": `Tipo di notifica`,
        "es": `Tipo de notificaciones`,
        "pl": `Typ powiadomień`,
        "zh-cn": `通知类型`
    },
    "pushover instance": {
        "en": `Pushover Instance`,
        "de": `Pushover Instanz`,
        "ru": `Pushover Instance`,
        "pt": `Instância de Pushover`,
        "nl": `Pushover Instance`,
        "fr": `Instance Pushover`,
        "it": `Istanza pushover`,
        "es": `Instancia Pushover`,
        "pl": `Instalacja Pushover`,
        "zh-cn": `Pushover实例`
    },
    "telegram instance": {
        "en": `Telegram Instance`,
        "de": `Telegram Instanz`,
        "ru": `Telegram Instance`,
        "pt": `Instância de telegrama`,
        "nl": `Telegram-instantie`,
        "fr": `Instance de télégramme`,
        "it": `Istanza di Telegram`,
        "es": `Instancia de telegrama`,
        "pl": `Instancja telegramu`,
        "zh-cn": `电报实例`
    },
    "telegram receiver": {
        "en": `Telegram Receiver`,
        "de": `Telegram Empfänger`,
        "ru": `Telegram Receiver`,
        "pt": `Receptor de telegrama`,
        "nl": `Telegram-ontvanger`,
        "fr": `Récepteur télégramme`,
        "it": `Telegram Receiver`,
        "es": `Receptor de telegramas`,
        "pl": `Odbiornik telegramu`,
        "zh-cn": `电报接收器`
    },
    "Decryption but no crypto lib": {
        "en": `Credentials encrypted with AES-256-CEC but browser does not provide a decryption possibility!`,
        "de": `Mit AES-256-CEC verschlüsselte Anmeldeinformationen, aber der Browser bietet keine Entschlüsselungsmöglichkeit!`,
        "ru": `Учетные данные зашифрованы с помощью AES-256-CEC, но браузер не обеспечивает возможность расшифровки!`,
        "pt": `Credenciais criptografadas com o AES-256-CEC, mas o navegador não oferece a possibilidade de descriptografia!`,
        "nl": `Referenties gecodeerd met AES-256-CEC maar browser biedt geen decoderingsmogelijkheid!`,
        "fr": `Les informations d'identification cryptées avec AES-256-CEC mais le navigateur ne fournit pas de possibilité de décryptage!`,
        "it": `Credenziali crittografate con AES-256-CEC ma il browser non offre la possibilità di decrittazione!`,
        "es": `¡Credenciales cifradas con AES-256-CEC pero el navegador no ofrece la posibilidad de descifrado!`,
        "pl": `Poświadczenia zaszyfrowane za pomocą AES-256-CEC, ale przeglądarka nie zapewnia możliwości odszyfrowania!`,
        "zh-cn": `使用AES-256-CEC加密的凭证，但浏览器不提供解密的可能性！`
    },
    "Provided key too short on encrypt": {
        "en": `The provided key is too short, fell back to standard encryption!`,
        "de": `Der mitgelieferte Schlüssel ist zu kurz, auf Standardverschlüsselung zurückgegriffen!`,
        "ru": `Предоставленный ключ слишком короткий, вернулся к стандартному шифрованию!`,
        "pt": `A chave fornecida é muito curta, voltou à criptografia padrão!`,
        "nl": `De verstrekte sleutel is te kort, viel terug op standaardcodering!`,
        "fr": `La clé fournie est trop courte, retombée au chiffrement standard!`,
        "it": `La chiave fornita è troppo corta, è tornato alla crittografia standard!`,
        "es": `La clave proporcionada es demasiado corta, ¡recurrió al cifrado estándar!`,
        "pl": `Podany klucz jest za krótki, wrócił do standardowego szyfrowania!`,
        "zh-cn": `提供的密钥太短，无法使用标准加密！`
    },
    "Crypto not available on encrypt": {
        "en": `Your browser does not provide a encryption possibility for AES-256-CEC. Fallback to standard encryption!`,
        "de": `Ihr Browser bietet keine Verschlüsselungsmöglichkeit für AES-256-CEC. Rückgriff auf Standardverschlüsselung!`,
        "ru": `Ваш браузер не предоставляет возможности шифрования для AES-256-CEC. Откат к стандартному шифрованию!`,
        "pt": `O seu navegador não oferece uma possibilidade de criptografia para o AES-256-CEC. Fallback para criptografia padrão!`,
        "nl": `Uw browser biedt geen coderingsmogelijkheid voor AES-256-CEC. Terugvallen op standaardcodering!`,
        "fr": `Votre navigateur ne fournit pas de possibilité de cryptage pour AES-256-CEC. Retour au cryptage standard!`,
        "it": `Il tuo browser non offre la possibilità di crittografia per AES-256-CEC. Fallback alla crittografia standard!`,
        "es": `Su navegador no proporciona una posibilidad de cifrado para AES-256-CEC. ¡Recurrir al cifrado estándar!`,
        "pl": `Twoja przeglądarka nie zapewnia możliwości szyfrowania dla AES-256-CEC. Powrót do standardowego szyfrowania!`,
        "zh-cn": `您的浏览器未提供AES-256-CEC加密的可能性。退回标准加密！`
    }
};
